package com.nagarsetu.core.ui.strings

import androidx.compose.runtime.compositionLocalOf

data class BottomNavStrings(
    val navHome: String,
    val navMap: String,
    val navRaksha: String,
    val navServices: String,
    val navReports: String,
    val navProfile: String,
    val navHomeDesc: String,
    val navMapDesc: String,
    val navRakshaDesc: String,
    val navServicesDesc: String,
    val navReportsDesc: String,
    val navProfileDesc: String
)

data class CommonStrings(
    val closeBtn: String,
    val backBtn: String,
    val cancelBtn: String,
    val nextBtn: String,
    val saveBtn: String,
    val addBtn: String,
    val submitBtn: String,
    val camera: String,
    val gallery: String,
    val search: String,
    val status: String,
    val loading: String
)

data class DashboardStrings(
    val cityPlatform: String,
    val sosRaksha: String,
    val tapForHelp: String,
    val cityStatus: String,
    val allSystemsNormal: String,
    val liveCityMap: String,
    val cityProgress: String,
    val casesResolved: String,
    val total: String,
    val quickReport: String,
    val potholes: String,
    val garbage: String,
    val streetlights: String,
    val smartServices: String,
    val recentEvents: String,
    val liveAlertsSupabase: String,
    val cityNews: String
)

data class RoadWatchStrings(
    val roadWatchTitle: String,
    val roadWatchSub: String,
    val tabReport: String,
    val tabTrack: String,
    val tabHeatmap: String,
    val stepType: String,
    val stepPhoto: String,
    val stepDetails: String,
    val stepConfirm: String,
    val reportHeading: String,
    val severityHeading: String,
    val addPhotoLocHeading: String,
    val aiAnalysing: String,
    val photoCaptured: String,
    val confidence: String,
    val useGps: String,
    val location: String,
    val description: String,
    val describeIssue: String,
    val reviewSubmit: String,
    val submitting: String,
    val drainage: String,
    val encroachment: String,
    val otherIssue: String,
    val captureEvidence: String,
    val selectCategory: String,
    val pinLocation: String,
    val issueLocation: String,
    val nearestAuthority: String,
    val submittedSuccessfully: String,
    val municipalNotified: String
)

data class RakshaStrings(
    val rakshaSubtitle: String,
    val rakshaProtected: String,
    val rakshaSosActive: String,
    val rakshaInstruction: String,
    val rakshaQuickActions: String,
    val rakshaLiveTrack: String,
    val rakshaFakeCall: String,
    val rakshaSosNow: String,
    val rakshaGuide: String,
    val rakshaPolice: String,
    val rakshaSettings: String,
    val rakshaLiveLocationSharing: String,
    val rakshaLocationSharingSub: String,
    val rakshaWearOsWatch: String,
    val rakshaNearestPoliceStation: String,
    val emergencyResponseActive: String,
    val emergencyGoldenHour: String,
    val emergencyNearestTrauma: String,
    val emergencyQuickEscape: String,
    val emergencySafetyTip: String,
    val emergencySafetyTipBody: String,
    val emergencyFakeCallBtn: String,
    val emergencyAddContact: String,
    val active: String,
    val crownInstruction: String,
    val pairWatchInstruction: String,
    val testSos: String,
    val mom: String,
    val incomingCall: String,
    val decline: String,
    val answer: String,
    val swipeToAnswer: String,
    val scheduleFakeCall: String,
    val emergencyShield: String,
    val holdSosInstruction: String,
    val sosActivated: String,
    val activeFor: String,
    val helpOnWay: String,
    val callPolice: String,
    val ambulance: String,
    val loadingCrimeData: String,
    val deactivateShield: String,
    val describeEmergency: String,
    val triagePlaceholder: String,
    val etaLabel: String
)

data class ServiceStrings(
    val parkEaseTitle: String,
    val parkEaseSub: String,
    val chargeUpTitle: String,
    val chargeUpSub: String,
    val greenRouteTitle: String,
    val greenRouteSub: String,
    val driveLegalTitle: String,
    val driveLegalSub: String,
    val healthWatchTitle: String,
    val healthWatchSub: String,
    val predictiveTitle: String,
    val predictiveSub: String,
    val servicePredictive: String,
    val servicePredictiveDesc: String,
    val serviceDriveLegal: String,
    val serviceDriveLegalDesc: String,
    val serviceHealthWatch: String,
    val serviceHealthWatchDesc: String,
    val serviceRoadWatch: String,
    val serviceRoadWatchDesc: String,
    val serviceParkEase: String,
    val serviceParkEaseDesc: String,
    val serviceChargeUp: String,
    val serviceChargeUpDesc: String,
    val serviceGreenRoute: String,
    val serviceGreenRouteDesc: String,
    val aiAssistant: String,
    val aiAssistantDesc: String,
    val availableSlots: String,
    val bookNow: String,
    val holdSlot: String,
    val distance: String,
    val price: String,
    val perUnit: String,
    val perHr: String,
    val startCharging: String,
    val stopCharging: String,
    val ecoSaved: String,
    val navigate: String,
    val arrivalIn: String,
    val bus: String,
    val cycle: String,
    val auto: String,
    val metro: String,
    val train: String,
    val minSuffix: String,
    val kmSuffix: String,
    val free: String,
    val crowding: String,
    val low: String,
    val moderate: String,
    val high: String,
    val resolved: String,
    val pending: String,
    val critical: String,
    val fastCharge: String,
    val expiresIn: String,
    val kwhDelivered: String,
    val charging: String,
    val scanPlate: String,
    val finesInfo: String,
    val estimatedFine: String,
    val driveLegalGreeting: String,
    val cityHealthIndex: String,
    val outbreakHeatmap: String,
    val activeOutbreaks: String,
    val nearbyClinics: String,
    val goodCondition: String,
    val moderateConcern: String,
    val highConcern: String,
    val consult: String,
    val open: String,
    val closed: String,
    val away: String,
    val activeCases: String,
    val allServices: String,
    val emergencyContacts: String,
    val nearbyHospitals: String,
    val trafficUpdates: String,
    val cityAnnouncements: String,
    val findBookParking: String,
    val searchNearMe: String,
    val findParkingBtn: String,
    val filters: String,
    val covered: String,
    val evCharging: String
)

data class ProfileStrings(
    val guestUser: String,
    val verifiedUser: String,
    val signInWithPhone: String,
    val logoutSession: String,
    val signInToSync: String,
    val sectionAccountSettings: String,
    val personalInfo: String,
    val personalInfoSub: String,
    val updateNameSub: String,
    val alertSettings: String,
    val alertSettingsSub: String,
    val language: String,
    val languageSub: String,
    val sectionSafetyEmergency: String,
    val trustedContacts: String,
    val trustedContactsSub: String,
    val medicalEmergencyInfo: String,
    val medicalEmergencyInfoSub: String,
    val sectionSupportLegal: String,
    val helpFaq: String,
    val helpFaqSub: String,
    val privacyPolicy: String,
    val privacyPolicySub: String,
    val aboutApp: String,
    val aboutAppSub: String,
    val alertSettingsTitle: String,
    val emergencySosAlerts: String,
    val emergencySosAlertsSub: String,
    val civicReportsUpdate: String,
    val civicReportsUpdateSub: String,
    val cityNewsAdvisories: String,
    val cityNewsAdvisoriesSub: String,
    val appLanguageTitle: String,
    val langEnglish: String,
    val langHindi: String,
    val personalInfoTitle: String,
    val updateIdentityHint: String,
    val fullName: String,
    val emailAddress: String,
    val saveChanges: String,
    val trustedContactsTitle: String,
    val trustedContactsHint: String,
    val addContactTitle: String,
    val nameLabel: String,
    val phoneLabel: String,
    val relationLabel: String,
    val medicalInfoTitle: String,
    val bloodGroup: String,
    val allergies: String,
    val currentMedications: String,
    val saveMedicalInfo: String,
    val helpFaqTitle: String,
    val faqItems: List<Pair<String, String>>,
    val privacyPolicyTitle: String,
    val privacyPolicyBody: String,
    val aboutEdition: String,
    val aboutPoweredBy: String
)

data class PredictiveStrings(
    val liveMlRiskScore: String,
    val riskModelLoading: String,
    val cityCentreMlModel: String,
    val sevenDayForecast: String,
    val cityRiskHeatmap: String,
    val syncing: String,
    val live: String,
    val proactiveSafetyAlerts: String,
    val civicKnowledgeAi: String,
    val ragSearchPlaceholder: String,
    val aiInsight: String,
    val confidenceLabel: String,
    val bimstecDataHub: String,
    val citiesCount: String,
    val legendAccidents: String,
    val legendFloods: String,
    val legendCrime: String,
    val legendHealth: String,
    val riskLow: String,
    val riskModerate: String,
    val riskHigh: String,
    val riskSevere: String,
    val gridCellDetail: String,
    val dominantRisk: String,
    val latLabel: String,
    val lngLabel: String,
    val recImmediate: String,
    val recElevated: String,
    val recModerate: String,
    val recLow: String
)

data class AuthStrings(
    val loginTitle: String,
    val loginSub: String,
    val phoneNumber: String,
    val sendOtp: String,
    val signInGoogle: String,
    val continueGuest: String,
    val verifyPhone: String,
    val sentTo: String,
    val verifyLogin: String,
    val editPhone: String,
    val enterPhoneError: String,
    val enterOtpError: String,
    val success: String
)

data class MapStrings(
    val all: String,
    val mapLayers: String,
    val hospitals: String,
    val incidentsAlerts: String,
    val traffic: String,
    val details: String,
    val searchLocation: String
)

data class GenericStrings(
    val bhopal: String,
    val rising: String,
    val falling: String,
    val stable: String,
    val aiAssistantWelcome: String,
    val thinking: String,
    val goTo: String,
    val aqiLabel: String,
    val aqiGood: String,
    val aqiModerate: String,
    val aqiUnhealthy: String,
    val aqiHazardous: String,
    val lastUpdated: String,
    val healthRecommendations: String,
    val liveLocation: String,
    val viewOnMap: String,
    val pollutants: String,
    val recommendationGood: String,
    val recommendationModerate: String,
    val recommendationUnhealthy: String,
    val recommendationHazardous: String
)

/**
 * All user-facing strings for NagarSetu.
 * Split into smaller data classes to avoid java.lang.VerifyError (too many fields).
 */
data class AppStrings(
    val nav: BottomNavStrings,
    val common: CommonStrings,
    val dashboard: DashboardStrings,
    val roadWatch: RoadWatchStrings,
    val raksha: RakshaStrings,
    val service: ServiceStrings,
    val profile: ProfileStrings,
    val predictive: PredictiveStrings,
    val auth: AuthStrings,
    val map: MapStrings,
    val generic: GenericStrings
)

val EnglishStrings = AppStrings(
    nav = BottomNavStrings(
        navHome = "Home",
        navMap = "Map",
        navRaksha = "Raksha",
        navServices = "Services",
        navReports = "Reports",
        navProfile = "Profile",
        navHomeDesc = "Home dashboard",
        navMapDesc = "Live city map",
        navRakshaDesc = "Raksha personal safety",
        navServicesDesc = "City services menu",
        navReportsDesc = "Report civic issues",
        navProfileDesc = "Your profile"
    ),
    common = CommonStrings(
        closeBtn = "CLOSE",
        backBtn = "Back",
        cancelBtn = "Cancel",
        nextBtn = "Next",
        saveBtn = "Save",
        addBtn = "Add",
        submitBtn = "Submit Report",
        camera = "Camera",
        gallery = "Gallery",
        search = "Search",
        status = "Status",
        loading = "Loading..."
    ),
    dashboard = DashboardStrings(
        cityPlatform = "Smart City Platform",
        sosRaksha = "SOS / RAKSHA",
        tapForHelp = "TAP FOR EMERGENCY HELP",
        cityStatus = "CITY STATUS",
        allSystemsNormal = "All Systems Normal",
        liveCityMap = "Live City Map",
        cityProgress = "CITY PROGRESS",
        casesResolved = "Cases Resolved",
        total = "Total",
        quickReport = "Quick Report",
        potholes = "Potholes",
        garbage = "Garbage",
        streetlights = "Streetlights",
        smartServices = "Smart Services",
        recentEvents = "Recent Events",
        liveAlertsSupabase = "Live Alerts (Supabase)",
        cityNews = "City News & Updates"
    ),
    roadWatch = RoadWatchStrings(
        roadWatchTitle = "RoadWatch",
        roadWatchSub = "Bhopal Road Hazard Analysis",
        tabReport = "Report",
        tabTrack = "Track",
        tabHeatmap = "Heatmap",
        stepType = "Type",
        stepPhoto = "Photo",
        stepDetails = "Details",
        stepConfirm = "Confirm",
        reportHeading = "What issue are you reporting?",
        severityHeading = "How severe is the issue?",
        addPhotoLocHeading = "Add Photo & Location",
        aiAnalysing = "AI Analysing photo...",
        photoCaptured = "Photo captured",
        confidence = "Confidence",
        useGps = "Use GPS",
        location = "Location",
        description = "Description",
        describeIssue = "Describe the issue...",
        reviewSubmit = "Review & Submit",
        submitting = "Submitting your report...",
        drainage = "Drainage",
        encroachment = "Encroachment",
        otherIssue = "Other Issue",
        captureEvidence = "Capture Evidence",
        selectCategory = "Select Category",
        pinLocation = "Pin Location",
        issueLocation = "Issue Location",
        nearestAuthority = "Nearest Authority",
        submittedSuccessfully = "Submitted Successfully!",
        municipalNotified = "Municipal team notified."
    ),
    raksha = RakshaStrings(
        rakshaSubtitle = "Personal safety • Bhopal",
        rakshaProtected = "Protected",
        rakshaSosActive = "SOS Active",
        rakshaInstruction = "Shake phone 3× • Watch crown 3× • Tap above",
        rakshaQuickActions = "Quick Actions",
        rakshaLiveTrack = "Live Track",
        rakshaFakeCall = "Fake Call",
        rakshaSosNow = "SOS Now",
        rakshaGuide = "Guide",
        rakshaPolice = "Police",
        rakshaSettings = "Settings",
        rakshaLiveLocationSharing = "Live Location Sharing",
        rakshaLocationSharingSub = "Sharing with your trusted contacts",
        rakshaWearOsWatch = "Wear OS Watch",
        rakshaNearestPoliceStation = "Nearest Police Station",
        emergencyResponseActive = "EMERGENCY RESPONSE ACTIVE",
        emergencyGoldenHour = "Golden Hour",
        emergencyNearestTrauma = "Nearest Trauma Centre",
        emergencyQuickEscape = "Quick Escape",
        emergencySafetyTip = "Safety Tip",
        emergencySafetyTipBody = "In an unsafe situation, use 'Quick Escape' to receive a fake call.",
        emergencyFakeCallBtn = "Fake Call in",
        emergencyAddContact = "Add Contact",
        active = "ACTIVE",
        crownInstruction = "Crown 3× or tap → SOS",
        pairWatchInstruction = "Pair via the Wear OS companion app",
        testSos = "Test SOS",
        mom = "Mom",
        incomingCall = "Incoming call...",
        decline = "Decline",
        answer = "Answer",
        swipeToAnswer = "Swipe to answer or decline",
        scheduleFakeCall = "Schedule Fake Call",
        emergencyShield = "Emergency Shield",
        holdSosInstruction = "Hold the button for 3 seconds to trigger SOS",
        sosActivated = "SOS ACTIVATED",
        activeFor = "Active for",
        helpOnWay = "Help is on the way",
        callPolice = "Call Police",
        ambulance = "Ambulance",
        loadingCrimeData = "Loading crime data...",
        deactivateShield = "Deactivate Shield",
        describeEmergency = "Describe Emergency (for AI guidance)",
        triagePlaceholder = "e.g. car accident with severe bleeding",
        etaLabel = "ETA"
    ),
    service = ServiceStrings(
        parkEaseTitle = "ParkEase",
        parkEaseSub = "Live Parking in Bhopal",
        chargeUpTitle = "ChargeUp",
        chargeUpSub = "EV Charging Network",
        greenRouteTitle = "GreenRoute",
        greenRouteSub = "Eco-Friendly Transit",
        driveLegalTitle = "DriveLegal",
        driveLegalSub = "Traffic Rules & Support",
        healthWatchTitle = "HealthWatch",
        healthWatchSub = "City Health & Outbreaks",
        predictiveTitle = "Predictive AI",
        predictiveSub = "Bhopal Civic Forecasting",
        servicePredictive = "Predictive AI",
        servicePredictiveDesc = "Risk forecast & RAG assistant",
        serviceDriveLegal = "DriveLegal",
        serviceDriveLegalDesc = "Traffic rules & legal support",
        serviceHealthWatch = "HealthWatch",
        serviceHealthWatchDesc = "City health & outbreak alerts",
        serviceRoadWatch = "RoadWatch",
        serviceRoadWatchDesc = "AI Pothole & infrastructure reporting",
        serviceParkEase = "ParkEase",
        serviceParkEaseDesc = "Live parking & QR tickets",
        serviceChargeUp = "ChargeUp",
        serviceChargeUpDesc = "EV stations & live charging SOC",
        serviceGreenRoute = "GreenRoute",
        serviceGreenRouteDesc = "Eco-friendly transit",
        aiAssistant = "NagarSetu AI",
        aiAssistantDesc = "Your intelligent city guide",
        availableSlots = "Available Slots",
        bookNow = "Book Now",
        holdSlot = "Hold Slot",
        distance = "Distance",
        price = "Price",
        perUnit = "per unit",
        perHr = "per hr",
        startCharging = "Start Charging",
        stopCharging = "Stop Charging",
        ecoSaved = "Saved",
        navigate = "Navigate",
        arrivalIn = "Arrival in",
        bus = "Bus",
        cycle = "Cycle",
        auto = "Auto",
        metro = "Metro",
        train = "Train",
        minSuffix = "min",
        kmSuffix = "km",
        free = "Free",
        crowding = "Crowding",
        low = "Low",
        moderate = "Moderate",
        high = "High",
        resolved = "Resolved",
        pending = "Pending",
        critical = "Critical",
        fastCharge = "Fast (>50kW)",
        expiresIn = "Expires in",
        kwhDelivered = "kWh delivered",
        charging = "Charging",
        scanPlate = "Scan Plate",
        finesInfo = "Fines Info",
        estimatedFine = "Estimated Fine",
        driveLegalGreeting = "Hello! I'm the DriveLegal AI. Ask me about traffic rules, fines, or legal queries in Bhopal.",
        cityHealthIndex = "City Health Index",
        outbreakHeatmap = "Outbreak Heatmap",
        activeOutbreaks = "Active Outbreaks",
        nearbyClinics = "Nearby Clinics",
        goodCondition = "Good condition",
        moderateConcern = "Moderate concern",
        highConcern = "High concern",
        consult = "Consult",
        open = "Open",
        closed = "Closed",
        away = "away",
        activeCases = "active cases",
        allServices = "All Services",
        emergencyContacts = "Emergency Contacts",
        nearbyHospitals = "Nearby Hospitals",
        trafficUpdates = "Traffic Updates",
        cityAnnouncements = "City Announcements",
        findBookParking = "Find & Book Parking",
        searchNearMe = "near me in real-time",
        findParkingBtn = "Find Parking",
        filters = "Filters",
        covered = "Covered",
        evCharging = "EV Charging"
    ),
    profile = ProfileStrings(
        guestUser = "Guest User",
        verifiedUser = "Verified User",
        signInWithPhone = "Sign in with Phone",
        logoutSession = "Logout Session",
        signInToSync = "Sign in to sync reports & track status",
        sectionAccountSettings = "Account Settings",
        personalInfo = "Personal Info",
        personalInfoSub = "Set your name",
        updateNameSub = "Update name",
        alertSettings = "Alert Settings",
        alertSettingsSub = "Manage city notifications",
        language = "Language",
        languageSub = "English (India)",
        sectionSafetyEmergency = "Safety & Emergency",
        trustedContacts = "Trusted Contacts",
        trustedContactsSub = "Manage safety contacts",
        medicalEmergencyInfo = "Medical Emergency Info",
        medicalEmergencyInfoSub = "Blood group, Allergies",
        sectionSupportLegal = "Support & Legal",
        helpFaq = "Help & FAQ",
        helpFaqSub = "Common queries about NagarSetu",
        privacyPolicy = "Privacy Policy",
        privacyPolicySub = "How we protect your data",
        aboutApp = "About App",
        aboutAppSub = "Version 2.0.0 (Bhopal Edition)",
        alertSettingsTitle = "Alert Settings",
        emergencySosAlerts = "Emergency SOS Alerts",
        emergencySosAlertsSub = "Get notified when SOS is triggered near you",
        civicReportsUpdate = "Civic Reports Update",
        civicReportsUpdateSub = "Status changes of your reported issues",
        cityNewsAdvisories = "City News & Advisories",
        cityNewsAdvisoriesSub = "Important announcements from BMC Bhopal",
        appLanguageTitle = "App Language",
        langEnglish = "English",
        langHindi = "Hindi (हिन्दी)",
        personalInfoTitle = "Personal Info",
        updateIdentityHint = "Update your identity on NagarSetu",
        fullName = "Full Name",
        emailAddress = "Email Address",
        saveChanges = "SAVE CHANGES",
        trustedContactsTitle = "Trusted Contacts",
        trustedContactsHint = "Manage up to 5 contacts who will be notified in emergency.",
        addContactTitle = "Add Contact",
        nameLabel = "Name",
        phoneLabel = "Phone",
        relationLabel = "Relation",
        medicalInfoTitle = "Medical Emergency Info",
        bloodGroup = "Blood Group",
        allergies = "Allergies",
        currentMedications = "Current Medications",
        saveMedicalInfo = "SAVE MEDICAL INFO",
        helpFaqTitle = "Help & FAQ",
        faqItems = listOf(
            "What should I do during a medical emergency?" to "Immediately press the SOS button in NagarSetu to alert nearby emergency services, share your live location, and contact emergency numbers quickly.",
            "How can I stay safe while traveling at night?" to "Always use well-lit routes, share your live location with trusted contacts, avoid isolated areas, and use verified transport services.",
            "What should I do if I notice suspicious activity in my area?" to "Report suspicious activity through the Civic Reporting feature in NagarSetu or contact local police immediately if the situation is serious.",
            "How can I stay safe during heavy rainfall or floods?" to "Avoid waterlogged roads, stay indoors when possible, monitor weather alerts, and use NagarSetu for emergency updates and safe route information.",
            "What precautions should I take while using public parking?" to "Park only in authorized areas, avoid leaving valuables visible, lock your vehicle properly, and use verified parking locations listed in ParkEase.",
            "What should I do if I face a road accident?" to "Move to a safe area if possible, contact emergency services, avoid crowding the accident site, and use NagarSetu SOS for rapid assistance.",
            "How can women improve personal safety while commuting alone?" to "Share trip details with trusted contacts, avoid deserted places, stay alert, and use the emergency SOS feature whenever needed.",
            "What should I do during poor AQI or air pollution conditions?" to "Limit outdoor activities, wear a mask, stay hydrated, and monitor AQI updates through NagarSetu Health Watch.",
            "How can I stay safe during fire emergencies?" to "Evacuate immediately, avoid elevators, use emergency exits, and contact fire emergency services through the SOS module.",
            "What are the basic cyber safety tips for smart city users?" to "Never share OTPs or passwords, avoid suspicious links, use strong passwords, and only access official NagarSetu services and verified platforms."
        ),
        privacyPolicyTitle = "Privacy Policy",
        privacyPolicyBody = "We take your privacy seriously. We collect minimal data for authentication and location mapping.",
        aboutEdition = "Bhopal Smart City Edition",
        aboutPoweredBy = "Powered by Kotlin & Supabase"
    ),
    predictive = PredictiveStrings(
        liveMlRiskScore = "Live ML Risk Score",
        riskModelLoading = "Risk model loading...",
        cityCentreMlModel = "city centre • ML model",
        sevenDayForecast = "7-Day Risk Forecast",
        cityRiskHeatmap = "City Risk Heatmap",
        syncing = "Syncing...",
        live = "Live",
        proactiveSafetyAlerts = "Proactive Safety Alerts",
        civicKnowledgeAi = "Civic Knowledge AI",
        ragSearchPlaceholder = "Ask about city infrastructure, risks...",
        aiInsight = "AI Insight",
        confidenceLabel = "Confidence",
        bimstecDataHub = "BIMSTEC Regional Data Hub",
        citiesCount = "cities",
        legendAccidents = "Accidents",
        legendFloods = "Floods",
        legendCrime = "Crime",
        legendHealth = "Health",
        riskLow = "Low",
        riskModerate = "Moderate",
        riskHigh = "High",
        riskSevere = "Severe",
        gridCellDetail = "Grid Cell Risk Detail",
        dominantRisk = "Dominant risk",
        latLabel = "Lat",
        lngLabel = "Lng",
        recImmediate = "🚨 Immediate action required. Deploy emergency resources and alert residents.",
        recElevated = "⚠️ Elevated risk. Increase monitoring. Pre-position response teams.",
        recModerate = "📋 Moderate risk. Regular patrol and civic maintenance advised.",
        recLow = "✅ Low risk. Continue standard civic operations."
    ),
    auth = AuthStrings(
        loginTitle = "NagarSetu Login",
        loginSub = "Access smart civic services",
        phoneNumber = "Phone Number",
        sendOtp = "Send OTP",
        signInGoogle = "Sign in with Google",
        continueGuest = "Continue as Guest",
        verifyPhone = "Verify Phone",
        sentTo = "Sent to",
        verifyLogin = "Verify & Login",
        editPhone = "Edit Phone Number",
        enterPhoneError = "Please enter your phone number",
        enterOtpError = "Please enter the 6-digit OTP",
        success = "Success"
    ),
    map = MapStrings(
        all = "All",
        mapLayers = "Map Layers",
        hospitals = "Hospitals",
        incidentsAlerts = "Incidents / Alerts",
        traffic = "Traffic",
        details = "Details",
        searchLocation = "Search location"
    ),
    generic = GenericStrings(
        bhopal = "Bhopal",
        rising = "↑ Rising",
        falling = "↓ Falling",
        stable = "→ Stable",
        aiAssistantWelcome = "Ask me about parking, SOS, challans, health, or green routes in Bhopal.",
        thinking = "Thinking...",
        goTo = "Go to",
        aqiLabel = "AQI",
        aqiGood = "Good",
        aqiModerate = "Moderate",
        aqiUnhealthy = "Unhealthy",
        aqiHazardous = "Hazardous",
        lastUpdated = "Last updated",
        healthRecommendations = "Health Recommendations",
        liveLocation = "Live Location",
        viewOnMap = "View on Map",
        pollutants = "Pollutants Breakdown",
        recommendationGood = "It's a great day for outdoor activities. Enjoy the fresh air!",
        recommendationModerate = "Air quality is acceptable. Sensitive individuals should limit prolonged outdoor exertion.",
        recommendationUnhealthy = "Everyone may begin to experience health effects. Avoid outdoor exercise.",
        recommendationHazardous = "Health alert: everyone may experience more serious health effects. Stay indoors."
    )
)

val HindiStrings = AppStrings(
    nav = BottomNavStrings(
        navHome = "होम",
        navMap = "मैप",
        navRaksha = "रक्षा",
        navServices = "सेवाएँ",
        navReports = "रिपोर्ट",
        navProfile = "प्रोफाइल",
        navHomeDesc = "होम डैशबोर्ड",
        navMapDesc = "लाइव शहर मैप",
        navRakshaDesc = "रक्षा व्यक्तिगत सुरक्षा",
        navServicesDesc = "शहरी सेवाएँ मेनू",
        navReportsDesc = "समस्याएँ रिपोर्ट करें",
        navProfileDesc = "आपका प्रोफाइल"
    ),
    common = CommonStrings(
        closeBtn = "बंद करें",
        backBtn = "पीछे",
        cancelBtn = "रद्द करें",
        nextBtn = "अगला",
        saveBtn = "सहेजें",
        addBtn = "जोड़ें",
        submitBtn = "रिपोर्ट सबमिट करें",
        camera = "कैमरा",
        gallery = "गैलरी",
        search = "खोजें",
        status = "स्थिति",
        loading = "लोड हो रहा है..."
    ),
    dashboard = DashboardStrings(
        cityPlatform = "स्मार्ट सिटी प्लेटफॉर्म",
        sosRaksha = "आपातकालीन / रक्षा",
        tapForHelp = "आपातकालीन मदद के लिए टैप करें",
        cityStatus = "शहर की स्थिति",
        allSystemsNormal = "सभी सिस्टम सामान्य हैं",
        liveCityMap = "लाइव सिटी मैप",
        cityProgress = "शहर की प्रगति",
        casesResolved = "मामले सुलझाए गए",
        total = "कुल",
        quickReport = "त्वरित रिपोर्ट",
        potholes = "सड़क के गड्ढे",
        garbage = "कचरा",
        streetlights = "स्ट्रीटलाइट",
        smartServices = "स्मार्ट सेवाएँ",
        recentEvents = "हाल की घटनाएँ",
        liveAlertsSupabase = "लाइव अलर्ट (डेटाबेस)",
        cityNews = "शहर के समाचार"
    ),
    roadWatch = RoadWatchStrings(
        roadWatchTitle = "रोड वॉच",
        roadWatchSub = "भोपाल सड़क खतरा विश्लेषण",
        tabReport = "रिपोर्ट",
        tabTrack = "ट्रैक",
        tabHeatmap = "हीटमैप",
        stepType = "प्रकार",
        stepPhoto = "फोटो",
        stepDetails = "विवरण",
        stepConfirm = "पुष्टि",
        reportHeading = "आप किस समस्या की रिपोर्ट कर रहे हैं?",
        severityHeading = "समस्या कितनी गंभीर है?",
        addPhotoLocHeading = "फोटो और स्थान जोड़ें",
        aiAnalysing = "AI फोटो का विश्लेषण कर रहा है...",
        photoCaptured = "फोटो ले ली गई है",
        confidence = "सटीकता",
        useGps = "GPS का उपयोग करें",
        location = "स्थान",
        description = "विवरण",
        describeIssue = "समस्या का वर्णन करें...",
        reviewSubmit = "समीक्षा और सबमिट",
        submitting = "आपकी रिपोर्ट सबमिट हो रही है...",
        drainage = "जल निकासी",
        encroachment = "अतिक्रमण",
        otherIssue = "अन्य समस्या",
        captureEvidence = "सबूत कैप्चर करें",
        selectCategory = "श्रेणी चुनें",
        pinLocation = "स्थान पिन करें",
        issueLocation = "समस्या का स्थान",
        nearestAuthority = "निकटतम प्राधिकरण",
        submittedSuccessfully = "सफलतापूर्वक सबमिट किया गया!",
        municipalNotified = "नगरपालिका टीम को सूचित कर दिया गया है।"
    ),
    raksha = RakshaStrings(
        rakshaSubtitle = "व्यक्तिगत सुरक्षा • भोपाल",
        rakshaProtected = "सुरक्षित",
        rakshaSosActive = "आपातकालीन SOS सक्रिय",
        rakshaInstruction = "फोन को 3 बार हिलाएं • वॉच बटन दबाएं • ऊपर टैप करें",
        rakshaQuickActions = "त्वरित कार्रवाई",
        rakshaLiveTrack = "लाइव ट्रैक",
        rakshaFakeCall = "फेक कॉल",
        rakshaSosNow = "अभी SOS",
        rakshaGuide = "गाइड",
        rakshaPolice = "पुलिस",
        rakshaSettings = "सेटिंग्स",
        rakshaLiveLocationSharing = "लाइव लोकेशन शेयरिंग",
        rakshaLocationSharingSub = "विश्वसनीय संपर्कों के साथ शेयर करें",
        rakshaWearOsWatch = "Wear OS वॉच",
        rakshaNearestPoliceStation = "निकटतम पुलिस स्टेशन",
        emergencyResponseActive = "आपातकालीन प्रतिक्रिया सक्रिय",
        emergencyGoldenHour = "गोल्डन ऑवर",
        emergencyNearestTrauma = "निकटतम ट्रॉमा सेंटर",
        emergencyQuickEscape = "त्वरित बचाव",
        emergencySafetyTip = "सुरक्षा टिप",
        emergencySafetyTipBody = "असुरक्षित स्थिति में, खुद को बचाने के लिए 'फेक कॉल' का उपयोग करें।",
        emergencyFakeCallBtn = "फेक कॉल",
        emergencyAddContact = "संपर्क जोड़ें",
        active = "सक्रिय",
        crownInstruction = "बटन को 3 बार दबाएं या टैप करें → SOS",
        pairWatchInstruction = "Wear OS कंपैनियन ऐप के माध्यम से पेयर करें",
        testSos = "SOS टेस्ट करें",
        mom = "माँ",
        incomingCall = "इनकमिंग कॉल...",
        decline = "अस्वीकार करें",
        answer = "उत्तर दें",
        swipeToAnswer = "उत्तर देने या अस्वीकार करने के लिए स्वाइप करें",
        scheduleFakeCall = "फेक कॉल शेड्यूल करें",
        emergencyShield = "आपातकालीन ढाल",
        holdSosInstruction = "SOS ट्रिगर करने के लिए बटन को 3 सेकंड तक दबाकर रखें",
        sosActivated = "SOS सक्रिय",
        activeFor = "सक्रिय समय",
        helpOnWay = "मदद रास्ते में है",
        callPolice = "पुलिस को कॉल करें",
        ambulance = "एम्बुलेंस",
        loadingCrimeData = "अपराध डेटा लोड हो रहा है...",
        deactivateShield = "शील्ड बंद करें",
        describeEmergency = "आपातकाल का वर्णन करें (AI मार्गदर्शन के लिए)",
        triagePlaceholder = "जैसे: गंभीर रक्तस्राव के साथ कार दुर्घटना",
        etaLabel = "ETA"
    ),
    service = ServiceStrings(
        parkEaseTitle = "पार्क ईज़",
        parkEaseSub = "भोपाल में लाइव पार्किंग",
        chargeUpTitle = "चार्ज अप",
        chargeUpSub = "EV चार्जिंग नेटवर्क",
        greenRouteTitle = "ग्रीन रूट",
        greenRouteSub = "पर्यावरण अनुकूल मार्ग",
        driveLegalTitle = "ड्राइव लीगल",
        driveLegalSub = "यातायात नियम और सहायता",
        healthWatchTitle = "हेल्थ वॉच",
        healthWatchSub = "शहर का स्वास्थ्य और बीमारी",
        predictiveTitle = "पूर्वानुमान AI",
        predictiveSub = "भोपाल नागरिक पूर्वानुमान",
        servicePredictive = "पूर्वानुमान AI",
        servicePredictiveDesc = "जोखिम पूर्वानुमान और AI सहायक",
        serviceDriveLegal = "ड्राइव लीगल",
        serviceDriveLegalDesc = "यातायात नियम और कानूनी सहायता",
        serviceHealthWatch = "हेल्थ वॉच",
        serviceHealthWatchDesc = "शहर का स्वास्थ्य और बीमारी अलर्ट",
        serviceRoadWatch = "रोड वॉच",
        serviceRoadWatchDesc = "AI गड्ढे और बुनियादी ढांचा रिपोर्टिंग",
        serviceParkEase = "पार्क ईज़",
        serviceParkEaseDesc = "लाइव पार्किंग और QR टिकट",
        serviceChargeUp = "चार्ज अप",
        serviceChargeUpDesc = "EV स्टेशन और लाइव चार्जिंग स्थिति",
        serviceGreenRoute = "ग्रीन रूट",
        serviceGreenRouteDesc = "पर्यावरण अनुकूल मार्ग",
        aiAssistant = "नगरसेतु AI",
        aiAssistantDesc = "आपका बुद्धिमान शहर मार्गदर्शक",
        availableSlots = "उपलब्ध स्लॉट",
        bookNow = "अभी बुक करें",
        holdSlot = "स्लॉट होल्ड करें",
        distance = "दूरी",
        price = "कीमत",
        perUnit = "प्रति यूनिट",
        perHr = "प्रति घंटा",
        startCharging = "चार्जिंग शुरू करें",
        stopCharging = "चार्जिंग रोकें",
        ecoSaved = "बचत",
        navigate = "रास्ता देखें",
        arrivalIn = "आगमन",
        bus = "बस",
        cycle = "साइकिल",
        auto = "ऑटो",
        metro = "मेट्रो",
        train = "ट्रेन",
        minSuffix = "मिनट",
        kmSuffix = "किमी",
        free = "मुफ्त",
        crowding = "भीड़",
        low = "कम",
        moderate = "मध्यम",
        high = "अधिक",
        resolved = "सुलझाया गया",
        pending = "लंबित",
        critical = "गंभीर",
        fastCharge = "फास्ट (>50kW)",
        expiresIn = "समाप्त होने का समय",
        kwhDelivered = "kWh वितरित",
        charging = "चार्ज हो रहा है",
        scanPlate = "प्लेट स्कैन करें",
        finesInfo = "जुर्माने की जानकारी",
        estimatedFine = "अनुमानित जुर्माना",
        driveLegalGreeting = "नमस्ते! मैं ड्राइवलीगल AI हूँ। मुझसे भोपाल में यातायात नियमों, जुर्माने या कानूनी प्रश्नों के बारे में पूछें।",
        cityHealthIndex = "शहर स्वास्थ्य सूचकांक",
        outbreakHeatmap = "प्रकोप हीटमैप",
        activeOutbreaks = "सक्रिय प्रकोप",
        nearbyClinics = "निकटतम क्लीनिक",
        goodCondition = "अच्छी स्थिति",
        moderateConcern = "मध्यम चिंता",
        highConcern = "उच्च चिंता",
        consult = "परामर्श",
        open = "खुला है",
        closed = "बंद है",
        away = "दूर",
        activeCases = "सक्रिय मामले",
        allServices = "सभी सेवाएँ",
        emergencyContacts = "आपातकालीन संपर्क",
        nearbyHospitals = "निकटतम अस्पताल",
        trafficUpdates = "ट्रैफिक अपडेट",
        cityAnnouncements = "शहर की घोषणाएँ",
        findBookParking = "पार्किंग खोजें और बुक करें",
        searchNearMe = "मेरे पास रियल-टाइम में",
        findParkingBtn = "पार्किंग खोजें",
        filters = "फिल्टर",
        covered = "कवर्ड",
        evCharging = "EV चार्जिंग"
    ),
    profile = ProfileStrings(
        guestUser = "अतिथि उपयोगकर्ता",
        verifiedUser = "सत्यापित उपयोगकर्ता",
        signInWithPhone = "Sign in with Phone",
        logoutSession = "लॉगआउट करें",
        signInToSync = "रिपोर्ट सिंक करने के लिए साइन इन करें",
        sectionAccountSettings = "खाता सेटिंग्स",
        personalInfo = "व्यक्तिगत जानकारी",
        personalInfoSub = "अपना नाम दर्ज करें",
        updateNameSub = "नाम अपडेट करें",
        alertSettings = "अलर्ट सेटिंग्स",
        alertSettingsSub = "सूचनाएं प्रबंधित करें",
        language = "भाषा",
        languageSub = "हिन्दी (भारत)",
        sectionSafetyEmergency = "सुरक्षा और आपातकाल",
        trustedContacts = "विश्वसनीय संपर्क",
        trustedContactsSub = "सुरक्षा संपर्क प्रबंधित करें",
        medicalEmergencyInfo = "चिकित्सा आपातकालीन जानकारी",
        medicalEmergencyInfoSub = "रक्त समूह, एलर्जी",
        sectionSupportLegal = "सहायता और कानूनी",
        helpFaq = "सहायता और FAQ",
        helpFaqSub = "नगरसेtu के बारे में सामान्य प्रश्न",
        privacyPolicy = "गोपनीयता नीति",
        privacyPolicySub = "डेटा सुरक्षा नीति",
        aboutApp = "ऐप के बारे में",
        aboutAppSub = "संस्करण 2.0.0 (भोपाल संस्करण)",
        alertSettingsTitle = "अलर्ट सेटिंग्स",
        emergencySosAlerts = "आपातकालीन SOS अलर्ट",
        emergencySosAlertsSub = "जब पास में SOS ट्रिगर हो तो सूचना पाएं",
        civicReportsUpdate = "नागरिक रिपोर्ट अपडेट",
        civicReportsUpdateSub = "आपकी रिपोर्ट की स्थिति में बदलाव",
        cityNewsAdvisories = "शहर समाचार और सलाह",
        cityNewsAdvisoriesSub = "BMC भोपाल से महत्वपूर्ण घोषणाएँ",
        appLanguageTitle = "ऐप भाषा",
        langEnglish = "English",
        langHindi = "हिन्दी",
        personalInfoTitle = "व्यक्तिगत जानकारी",
        updateIdentityHint = "नगरसेतु पर अपनी पहचान अपडेट करें",
        fullName = "पूरा नाम",
        emailAddress = "ईमेल पता",
        saveChanges = "बदलाव सहेजें",
        trustedContactsTitle = "विश्वसनीय संपर्क",
        trustedContactsHint = "आपातकाल में सूचित होने वाले 5 संपर्क प्रबंधित करें।",
        addContactTitle = "संपर्क जोड़ें",
        nameLabel = "नाम",
        phoneLabel = "फ़ोन",
        relationLabel = "संबंध",
        medicalInfoTitle = "चिकित्सा आपातकालीन जानकारी",
        bloodGroup = "रक्त समूह",
        allergies = "एलर्जी",
        currentMedications = "वर्तमान दवाइयाँ",
        saveMedicalInfo = "चिकित्सा जानकारी सहेजें",
        helpFaqTitle = "सहायता और FAQ",
        faqItems = listOf(
            "मेडिकल इमरजेंसी के दौरान मुझे क्या करना चाहिए?" to "आपातकालीन सेवाओं को सचेत करने, अपना लाइव लोकेशन साझा करने और आपातकालीन नंबरों से जल्दी संपर्क करने के लिए नगरसेतु में तुरंत SOS बटन दबाएं।",
            "रात में यात्रा करते समय मैं सुरक्षित कैसे रह सकता हूँ?" to "हमेशा अच्छी रोशनी वाले रास्तों का उपयोग करें, विश्वसनीय संपर्कों के साथ अपना लाइव लोकेशन साझा करें, सुनसान इलाकों से बचें और सत्यापित परिवहन सेवाओं का उपयोग करें।",
            "अगर मुझे अपने क्षेत्र में संदिग्ध गतिविधि दिखाई दे तो मुझे क्या करना चाहिए?" to "नगरसेतु में नागरिक रिपोर्टिंग सुविधा के माध्यम से संदिग्ध गतिविधि की रिपोर्ट करें या स्थिति गंभीर होने पर तुरंत स्थानीय पुलिस से संपर्क करें।",
            "भारी बारिश या बाढ़ के दौरान मैं सुरक्षित कैसे रह सकता हूँ?" to "जलभराव वाली सड़कों से बचें, यथासंभव घर के अंदर रहें, मौसम की चेतावनियों पर नज़र रखें और आपातकालीन अपडेट और सुरक्षित मार्ग की जानकारी के लिए नगरसेतु का उपयोग करें।",
            "सार्वजनिक पार्किंग का उपयोग करते समय मुझे क्या सावधानियां बरतनी चाहिए?" to "केवल अधिकृत क्षेत्रों में पार्क करें, कीमती सामान न छोड़ें, अपने वाहन को ठीक से लॉक करें और पार्क ईज़ में सूचीबद्ध सत्यापित पार्किंग स्थानों का उपयोग करें।",
            "सड़क दुर्घटना होने पर मुझे क्या करना चाहिए?" to "यदि संभव हो तो सुरक्षित क्षेत्र में जाएँ, आपातकालीन सेवाओं से संपर्क करें, दुर्घटना स्थल पर भीड़ न लगाएं और त्वरित सहायता के लिए नगरसेतु SOS का उपयोग करें।",
            "अकेले यात्रा करते समय महिलाएं व्यक्तिगत सुरक्षा में सुधार कैसे कर सकती हैं?" to "विश्वसनीय संपर्कों के साथ यात्रा विवरण साझा करें, सुनसान जगहों से बचें, सतर्क रहें और ज़रूरत पड़ने पर आपातकालीन SOS सुविधा का उपयोग करें।",
            "खराब AQI या वायु प्रदूषण की स्थिति में मुझे क्या करना चाहिए?" to "बाहरी गतिविधियों को सीमित करें, मास्क पहनें, हाइड्रेटेड रहें और नगरसेतु हेल्थ वॉच के माध्यम से AQI अपडेट पर नज़र रखें।",
            "आग लगने की स्थिति में मैं सुरक्षित कैसे रह सकता हूँ?" to "तुरंत बाहर निकलें, लिफ्ट का उपयोग न करें, आपातकालीन निकास का उपयोग करें और SOS मॉड्यूल के माध्यम से अग्निशमन आपातकालीन सेवाओं से संपर्क करें।",
            "स्मार्ट सिटी उपयोगकर्ताओं के लिए बुनियादी साइबर सुरक्षा युक्तियाँ क्या हैं?" to "कभी भी OTP या पासवर्ड साझा न करें, संदिग्ध लिंक से बचें, मजबूत पासवर्ड का उपयोग करें और केवल आधिकारिक नगरसेतु सेवाओं और सत्यापित प्लेटफार्मों का उपयोग करें।"
        ),
        privacyPolicyTitle = "गोपनीयता नीति",
        privacyPolicyBody = "हम आपकी गोपनीयता को गंभीरता से लेते हैं। हम केवल आवश्यक डेटा एकत्र करते हैं।",
        aboutEdition = "भोपाल स्मार्ट सिटी संस्करण",
        aboutPoweredBy = "Kotlin और Supabase द्वारा संचालित"
    ),
    predictive = PredictiveStrings(
        liveMlRiskScore = "लाइव ML जोखिम स्कोर",
        riskModelLoading = "जोखिम मॉडल लोड हो रहा है...",
        cityCentreMlModel = "शहर का केंद्र • ML मॉडल",
        sevenDayForecast = "7-दिवसीय जोखिम पूर्वानुमान",
        cityRiskHeatmap = "शहर जोखिम हीटमैप",
        syncing = "सिंक हो रहा है...",
        live = "लाइव",
        proactiveSafetyAlerts = "सक्रिय सुरक्षा अलर्ट",
        civicKnowledgeAi = "नागरिक ज्ञान AI",
        ragSearchPlaceholder = "शहर के बुनियादी ढांचे, जोखिमों के बारे में पूछें...",
        aiInsight = "AI अंतर्दृष्टि",
        confidenceLabel = "सटीकता",
        bimstecDataHub = "BIMSTEC क्षेत्रीय डेटा हब",
        citiesCount = "शहर",
        legendAccidents = "दुर्घटनाएं",
        legendFloods = "बाढ़",
        legendCrime = "अपराध",
        legendHealth = "स्वास्थ्य",
        riskLow = "कम",
        riskModerate = "मध्यम",
        riskHigh = "उच्च",
        riskSevere = "गंभीर",
        gridCellDetail = "ग्रिड सेल जोखिम विवरण",
        dominantRisk = "प्रमुख जोखिम",
        latLabel = "अक्षांश",
        lngLabel = "देशांतर",
        recImmediate = "🚨 तत्काल कार्रवाई आवश्यक। आपातकालीन संसाधन तैनात करें और निवासियों को सचेत करें।",
        recElevated = "⚠️ बढ़ा हुआ जोखिम। निगरानी बढ़ाएँ। प्रतिक्रिया टीमों को पहले से तैनात करें।",
        recModerate = "📋 मध्यम जोखिम। नियमित गश्त और नागरिक रखरखाव की सलाह दी जाती है।",
        recLow = "✅ कम जोखिम। मानक नागरिक संचालन जारी रखें।"
    ),
    auth = AuthStrings(
        loginTitle = "नगरसेतु लॉगिन",
        loginSub = "स्मार्ट नागरिक सेवाओं तक पहुँचें",
        phoneNumber = "फ़ोन नंबर",
        sendOtp = "OTP भेजें",
        signInGoogle = "Google के साथ साइन इन करें",
        continueGuest = "अतिथि के रूप में जारी रखें",
        verifyPhone = "फ़ोन सत्यापित करें",
        sentTo = "भेजा गया",
        verifyLogin = "सत्यापित करें और लॉगिन करें",
        editPhone = "फ़ोन नंबर बदलें",
        enterPhoneError = "कृपया अपना फ़ोन नंबर दर्ज करें",
        enterOtpError = "कृपया 6 अंकों का OTP दर्ज करें",
        success = "सफलता"
    ),
    map = MapStrings(
        all = "सभी",
        mapLayers = "मैप लेयर्स",
        hospitals = "अस्पताल",
        incidentsAlerts = "घटनाएँ / अलर्ट",
        traffic = "ट्रैफिक",
        details = "विवरण",
        searchLocation = "स्थान खोजें"
    ),
    generic = GenericStrings(
        bhopal = "भोपाल",
        rising = "↑ बढ़ रहा है",
        falling = "↓ कम हो रहा है",
        stable = "→ स्थिर",
        aiAssistantWelcome = "मुझसे भोपाल में पार्किंग, SOS, चालान, स्वास्थ्य या पर्यावरण अनुकूल मार्गों के बारे में पूछें।",
        thinking = "सोच रहा हूँ...",
        goTo = "पर जाएँ",
        aqiLabel = "AQI",
        aqiGood = "अच्छा",
        aqiModerate = "मध्यम",
        aqiUnhealthy = "अस्वस्थ",
        aqiHazardous = "खतरनाक",
        lastUpdated = "अंतिम अपडेट",
        healthRecommendations = "स्वास्थ्य सिफारिशें",
        liveLocation = "लाइव लोकेशन",
        viewOnMap = "मैप पर देखें",
        pollutants = "प्रदूषकों का विवरण",
        recommendationGood = "बाहरी गतिविधियों के लिए यह एक शानदार दिन है। ताजी हवा का आनंद लें!",
        recommendationModerate = "हवा की गुणवत्ता स्वीकार्य है। संवेदनशील व्यक्तियों को लंबे समय तक बाहरी परिश्रम को सीमित करना चाहिए।",
        recommendationUnhealthy = "सभी को स्वास्थ्य प्रभावों का अनुभव होना शुरू हो सकता है। बाहरी व्यायाम से बचें।",
        recommendationHazardous = "स्वास्थ्य चेतावनी: हर कोई अधिक गंभीर स्वास्थ्य प्रभावों का अनुभव कर सकता है। घर के अंदर रहें।"
    )
)

val LocalAppStrings = compositionLocalOf<AppStrings> { EnglishStrings }
